apiVersion: v1
data:
  allTranslations.json: |-
    {
      "catalog-react": {
        "en": {
            "entityKindPicker.title": "MyKind",
            "entityTypePicker.title": "MyType",
            "entityOwnerPicker.title": "MyOwner",
            "entityLifecyclePicker.title": "MyLifecycle",
            "fields.entityTagsPicker.title": "MyTags",
            "entityNamespacePicker.title": "MyNamespace",
            "entityProcessingStatusPicker.title": "MyProcessingStatus"
        }
      }
    }
kind: ConfigMap
metadata:
  name: all-translations
