apiVersion: v1
data:
  FOO: YmFy
  POSTGRES_DATABASE: cmhkaF9kYg==
  POSTGRES_HOST: PGluc3RhbmNlPi48cmVnaW9uPi5yZHMuYW1hem9uYXdzLmNvbQ==
  POSTGRES_PASSWORD: Y2hhbmdlbWU=
  POSTGRES_PORT: NTQzMg==
  POSTGRES_USER: cmhkaF91c2Vy
kind: Secret
metadata:
  name: my-rhdh-secrets
type: Opaque
