apiVersion: v1
kind: Secret
metadata:
  name: rhdh-database-secret
type: Opaque
stringData:
  POSTGRES_DB: rhdh
  POSTGRES_HOST: my-postgres.postgres.svc
  POSTGRES_PORT: "5432"
  POSTGRES_USER: rhdh_user
  POSTGRES_PASSWORD: changeme


